version: '3'
services:
  nginx:
    image: nginx:alpine
    command: nginx -g "daemon off;"
    container_name: nginx_task7
    network_mode: service:tomcat
    volumes:
      - "/task/7/nginx.conf:/etc/nginx/conf.d/default.conf"
  tomcat:
    image: tomcat:8.0
    working_dir: /usr/local/tomcat
    command: catalina.sh run
    container_name: tomcat_task7
    ports:
      - 10087:80
